version: '1.0'

services:
  django-api:
    container_name: api
    build:
      context: .
      args:
        - BUILD_COMMIT_SHA=local
    restart: always
    volumes:
      - .:/app
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:80
      "
    networks:
      - db_network
      - web_network

  web-nginx:
    container_name: web
    restart: always
    image: "nginx:latest"
    ports:
      - "8080:8080"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - django-api

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
