version: '1.0'

services:

  postgres:
    container_name: db
    image: "postgres:15.4"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
        - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c listen_addresses=*
    networks:
      - db_network

  django-api:
    container_name: api
    environment:
        - BUILD_COMMIT_SHA=local
        - FLAVOR=local
        - DJANGO_LOG_LEVEL=DEBUG
    build:
      context: .
      args:
        - BUILD_COMMIT_SHA=local
        - FLAVOR=local
    restart: always
    volumes:
      - .:/app
    command: >
      bash -c "
        python wait_for_postgres.py &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:80
      "
    depends_on:
      - postgres
    networks:
      - db_network
      - web_network

  web-nginx:
    container_name: web
    restart: always
    image: "nginx:latest"
    ports:
      - "8080:8080"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - django-api

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
